{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# DRKG - Knowledge Graph Embedding"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Install dependencies"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%%bash\n",
    "# We assume you are using a conda environment\n",
    "# torchvision==0.14.0 & torch==1.13 only work with CUDA==1.16 or CUDA==1.17 and python==3.10\n",
    "mamba create -n biomedgps python==3.10"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%%bash\n",
    "# If you have installed CUDA==1.16 or CUDA==1.17, you can use the following command to install torch==1.13\n",
    "# dglke is compatible with dgl==0.9.0 and dgl==0.9.0 only works with torch==1.13\n",
    "pip3 install torch==1.13 torchvision==0.14.0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%%bash\n",
    "pip install git+https://github.com/awslabs/dgl-ke.git#subdirectory=python && pip install ogb dgl==0.9.0"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Prepare Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%%bash\n",
    "mkdir test\n",
    "wget https://s3.us-west-2.amazonaws.com/dgl-data/dataset/DRKG/drkg.tar.gz -O test/drkg.tar.gz\n",
    "tar -xvzf test/drkg.tar.gz -C test/"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "drkg_file = \"test/drkg.tsv\"\n",
    "df = pd.read_csv(drkg_file, sep=\"\\t\", header=None)\n",
    "triples = df.values.tolist()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "num_triples = len(triples)\n",
    "num_triples"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os \n",
    "# Please make sure the output directory exist.\n",
    "seed = np.arange(num_triples)\n",
    "np.random.shuffle(seed)\n",
    "\n",
    "train_cnt = int(num_triples * 0.9)\n",
    "valid_cnt = int(num_triples * 0.05)\n",
    "train_set = seed[:train_cnt]\n",
    "train_set = train_set.tolist()\n",
    "valid_set = seed[train_cnt:train_cnt+valid_cnt].tolist()\n",
    "test_set = seed[train_cnt+valid_cnt:].tolist()\n",
    "\n",
    "os.makedirs(\"test/train\", exist_ok=True)\n",
    "\n",
    "with open(\"test/train/drkg_train.tsv\", 'w+') as f:\n",
    "    for idx in train_set:\n",
    "        f.writelines(\"{}\\t{}\\t{}\\n\".format(triples[idx][0], triples[idx][1], triples[idx][2]))\n",
    "        \n",
    "with open(\"test/train/drkg_valid.tsv\", 'w+') as f:\n",
    "    for idx in valid_set:\n",
    "        f.writelines(\"{}\\t{}\\t{}\\n\".format(triples[idx][0], triples[idx][1], triples[idx][2]))\n",
    "\n",
    "with open(\"test/train/drkg_test.tsv\", 'w+') as f:\n",
    "    for idx in test_set:\n",
    "        f.writelines(\"{}\\t{}\\t{}\\n\".format(triples[idx][0], triples[idx][1], triples[idx][2]))\n",
    "\n",
    "print(len(train_set), len(valid_set), len(test_set))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Train models with different hyperparameters"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Reading train triples....\n",
      "Finished. Read 5286834 train triples.\n",
      "Reading valid triples....\n",
      "Finished. Read 293713 valid triples.\n",
      "Reading test triples....\n",
      "Finished. Read 293714 test triples.\n",
      "/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dgl/_deprecate/graph.py:1023: DGLWarning: multigraph will be deprecated.DGL will treat all graphs as multigraph in the future.\n",
      "  dgl_warning(\"multigraph will be deprecated.\" \\\n",
      "|Train|: 5286834\n",
      "random partition 5286834 edges into 8 parts\n",
      "part 0 has 660855 edges\n",
      "part 1 has 660855 edges\n",
      "part 2 has 660855 edges\n",
      "part 3 has 660855 edges\n",
      "part 4 has 660855 edges\n",
      "part 5 has 660855 edges\n",
      "part 6 has 660855 edges\n",
      "part 7 has 660849 edges\n",
      "|valid|: 293713\n",
      "|test|: 293714\n",
      "Total initialize time 18.973 seconds\n",
      "Process Process-7:1:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 133, in decorated_function\n",
      "    raise exception.__class__(trace)\n",
      "torch.cuda.OutOfMemoryError: Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 121, in _queue_result\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 160, in async_update\n",
      "    grad_sum = (grad_values * grad_values).mean(1)\n",
      "torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 11.77 GiB total capacity; 5.10 MiB already allocated; 18.50 MiB free; 20.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF\n",
      "\n",
      "Process Process-2:1:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 133, in decorated_function\n",
      "    raise exception.__class__(trace)\n",
      "torch.cuda.OutOfMemoryError: Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 121, in _queue_result\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 160, in async_update\n",
      "    grad_sum = (grad_values * grad_values).mean(1)\n",
      "torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 11.77 GiB total capacity; 5.14 MiB already allocated; 18.50 MiB free; 20.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF\n",
      "\n",
      "Process Process-6:1:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 133, in decorated_function\n",
      "    raise exception.__class__(trace)\n",
      "torch.cuda.OutOfMemoryError: Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 121, in _queue_result\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 160, in async_update\n",
      "    grad_sum = (grad_values * grad_values).mean(1)\n",
      "torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 11.77 GiB total capacity; 5.08 MiB already allocated; 18.50 MiB free; 20.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF\n",
      "\n",
      "Process Process-5:1:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 133, in decorated_function\n",
      "    raise exception.__class__(trace)\n",
      "torch.cuda.OutOfMemoryError: Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 121, in _queue_result\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 160, in async_update\n",
      "    grad_sum = (grad_values * grad_values).mean(1)\n",
      "torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 11.77 GiB total capacity; 5.15 MiB already allocated; 18.50 MiB free; 20.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF\n",
      "\n",
      "Process Process-3:1:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 133, in decorated_function\n",
      "    raise exception.__class__(trace)\n",
      "torch.cuda.OutOfMemoryError: Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 121, in _queue_result\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 160, in async_update\n",
      "    grad_sum = (grad_values * grad_values).mean(1)\n",
      "torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 11.77 GiB total capacity; 5.10 MiB already allocated; 18.50 MiB free; 20.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF\n",
      "\n",
      "Process Process-4:1:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 133, in decorated_function\n",
      "    raise exception.__class__(trace)\n",
      "torch.cuda.OutOfMemoryError: Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 121, in _queue_result\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 160, in async_update\n",
      "    grad_sum = (grad_values * grad_values).mean(1)\n",
      "torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 11.77 GiB total capacity; 5.15 MiB already allocated; 18.50 MiB free; 20.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF\n",
      "\n",
      "^C\n",
      "Process Process-8:1:\n",
      "Process Process-1:1:\n",
      "Process Process-7:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/biomedgps/bin/dglke_train\", line 8, in <module>\n",
      "Process Process-4:\n",
      "Process Process-5:\n",
      "Process Process-6:\n",
      "Process Process-3:\n",
      "Process Process-2:\n",
      "    sys.exit(main())\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/train.py\", line 317, in main\n",
      "    proc.join()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 149, in join\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 128, in decorated_function\n",
      "    result, exception, trace = queue.get()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/queues.py\", line 103, in get\n",
      "    res = self._recv_bytes()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 221, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 419, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 384, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "KeyboardInterrupt\n",
      "    res = self._popen.wait(timeout)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/popen_fork.py\", line 43, in wait\n",
      "    return self.poll(os.WNOHANG if timeout == 0.0 else 0)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/popen_fork.py\", line 27, in poll\n",
      "    pid, sts = os.waitpid(self.pid, flag)\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 128, in decorated_function\n",
      "    result, exception, trace = queue.get()\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 128, in decorated_function\n",
      "    result, exception, trace = queue.get()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/queues.py\", line 103, in get\n",
      "    res = self._recv_bytes()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/queues.py\", line 103, in get\n",
      "    res = self._recv_bytes()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 221, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 221, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 419, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 419, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 384, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 384, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 128, in decorated_function\n",
      "    result, exception, trace = queue.get()\n",
      "KeyboardInterrupt\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/queues.py\", line 103, in get\n",
      "    res = self._recv_bytes()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "KeyboardInterrupt\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 221, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 419, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 128, in decorated_function\n",
      "    result, exception, trace = queue.get()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 384, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/queues.py\", line 103, in get\n",
      "    res = self._recv_bytes()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 221, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 419, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "KeyboardInterrupt\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 384, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 128, in decorated_function\n",
      "    result, exception, trace = queue.get()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/queues.py\", line 103, in get\n",
      "    res = self._recv_bytes()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 128, in decorated_function\n",
      "    result, exception, trace = queue.get()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 221, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/queues.py\", line 103, in get\n",
      "    res = self._recv_bytes()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 419, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 384, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 221, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 419, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/site-packages/dglke/models/pytorch/tensor_models.py\", line 128, in decorated_function\n",
      "    result, exception, trace = queue.get()\n",
      "KeyboardInterrupt\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 384, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/queues.py\", line 103, in get\n",
      "    res = self._recv_bytes()\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 221, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "KeyboardInterrupt\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 419, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/opt/conda/envs/biomedgps/lib/python3.10/multiprocessing/connection.py\", line 384, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "!DGLBACKEND=pytorch dglke_train --dataset drkg --data_path ./test/train --data_files drkg_train.tsv drkg_valid.tsv drkg_test.tsv --format 'raw_udd_hrt' --model_name TransE_l2 --batch_size 2048 --neg_sample_size 256 --hidden_dim 400 --gamma 12.0 --lr 0.1 --max_step 100000 --log_interval 1000 --batch_size_eval 16 -adv --regularization_coef 1.00E-07 --test --gpu 0 --num_proc 7 --neg_sample_size_eval 10000 --async_update --mix_cpu_gpu"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Model 1: TransE"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Model 2: TransR"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
